version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "angular",
    "react",
    "angularjs",
    "ember"
  ]
  environment = [
    "nodejs",
    "jquery"
  ]

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "docker"

[[transformers]]
name = "standardjs"